### ISSUE TITLE
Unable to set catalyst port and webpack port

### ISSUE THREAD

**Issue by anishagg17** [WormBase/website-public#11]
![Screenshot 2020-03-05 at 10 52 48 AM](https://user-images.githubusercontent.com/43617894/75950542-76a53080-5ecf-11ea-9ff6-61cf59413ab5.png)

**Comment by arteevraina** [comment]
@sibyl229 Please help..

**Comment by sibyl229** [comment]
@anishagg17 @arteevraina 
Could you try the following before running the `make local` command?

```
export CATALYST_PORT=[some_port_number] 
export WEBPACK_SERVER_PORT=[some_other_port_number]
```

If it works, you might want to include those in your .bash_profile (or the equivalents), so you don't need to set it every time.
