### ISSUE TITLE
Site is not getting rendered

### ISSUE THREAD

**Issue by anishagg17** [WormBase/website-public#13]
@sibyl229 please try to run the website locally by creating a new fork as we students are facing difficulties

i have made all the changes that you suggested earlier but still the site isn't loading 

` I have set ports`

![Screenshot 2020-03-07 at 2 19 31 AM](https://user-images.githubusercontent.com/43617894/76121621-18389900-601a-11ea-9f0c-dd5ad46919b5.png)

`When I run make local command`

![Screenshot 2020-03-07 at 2 20 59 AM](https://user-images.githubusercontent.com/43617894/76121712-4b7b2800-601a-11ea-8102-9fc96158ab98.png)

`but when i run it on localHost`

![Screenshot 2020-03-07 at 2 21 44 AM](https://user-images.githubusercontent.com/43617894/76121761-677ec980-601a-11ea-956e-3560332efc3c.png)

**Comment by anishagg17** [comment]
When i run it on localhost:CATALYST_PORT loading finishes after 2-3 mins and responds with localhost didn't send any data

**Comment by anishagg17** [comment]
![Screenshot 2020-03-07 at 2 24 20 AM](https://user-images.githubusercontent.com/43617894/76121896-d0664180-601a-11ea-881d-12626ad026e9.png)

**Comment by anishagg17** [comment]
Also , the api sends data only when id is known, please provide some demo ids too.

**Comment by alekhgupta1441** [comment]
I too am facing this error

**Comment by sibyl229** [comment]
Thanks for reporting this! I'm working out a solution. Will post here once it's ready.

The local development setup is rather new, and has many rough edges. Sorry about that.

**Comment by anishagg17** [comment]
@sibyl229 please provide id for apis

**Comment by sibyl229** [comment]
@anishagg17 Thanks for seeking clarification. I answered your question in #16. Please try to keep discussion within an issue on topic, and feel free to create additional issues when needed.

**Comment by anishagg17** [comment]
Thanks 👍

**Comment by sibyl229** [comment]
@anishagg17 the problem should be fixed now. But there is a bit of change to the instructions with an additional step to setting up `wormbase_local.conf`. Please refer to: https://github.com/WormBase/website-public#experimental-development-environment---local-option Thanks!

**Comment by anishagg17** [comment]
@sibyl  what changes do i need to do in `wormbase_local.conf` ?

**Comment by anishagg17** [comment]
@sibyl229  what changes do i need to do in wormbase_local.conf ?

**Comment by sibyl** [comment]
Sorry, no idea. Wrong "sibyl". :P




Sibyl Perkins
Sibyl Design, Inc.

**Comment by anishagg17** [comment]
Thanks @sibyl229 now it's working 👍
