### ISSUE TITLE
Could not connect to the docker daemon

### ISSUE THREAD

**Issue by arteevraina** [WormBase/website-public#15]
![Screenshot from 2020-03-07 03-59-43](https://user-images.githubusercontent.com/43968121/76127634-27bede80-6028-11ea-84e4-6b925accb24b.png)

**Comment by anishagg17** [comment]
bro your screenshot is broken i

**Comment by anishagg17** [comment]
Bro are you running docker desktop in background??

**Comment by anishagg17** [comment]
Because i too resolved it by running docker application in background, But i don't know if it wolud be resolved for  ubuntu

**Comment by anishagg17** [comment]
![Screenshot 2020-03-07 at 6 54 12 PM](https://user-images.githubusercontent.com/43617894/76144325-0bad5280-60a5-11ea-975d-48d319cd3fae.png)


@sibyl229 do we need to customise these kinds of tables?

**Comment by sibyl229** [comment]
Could you check if your docker version is 18.06.0 and above? It's required to use the docker-compose 3.7 syntax for `init`.
