### ISSUE TITLE
Fatal no repository found error

### ISSUE THREAD

**Issue by arteevraina** [WormBase/website-public#8]
On running ```
    git clone git://github.com/WormBase/website.git wormbase``` terminal gives error **fatal: remote error: 
  Repository not found.**. This step is given in manual_setup.md

**Comment by sibyl229** [comment]
@arteevraina thanks for your reporting the issue. Please clone the git@github.com:WormBase/website-public.git repo. It's a public mirror of git://github.com/WormBase/website.git .

**Comment by arteevraina** [comment]
I think `manual_setup.md` should be updated.
