### ISSUE TITLE
errors while setting up development mode

### ISSUE THREAD

**Issue by anishagg17** [WormBase/website-public#9]
![Screenshot 2020-03-03 at 3 05 36 PM](https://user-images.githubusercontent.com/43617894/75762298-720e3a00-5d60-11ea-9776-d9d376a3413b.png)

while running `make installdeps`

![Screenshot 2020-03-03 at 4 33 34 PM](https://user-images.githubusercontent.com/43617894/75769787-c0293a80-5d6c-11ea-988f-db4f3a5bc216.png)

**Comment by arteevraina** [comment]
@anishagg17 have u joined IRC of Open Genome Informatics?

**Comment by anishagg17** [comment]
Yep bro but there i got no response

**Comment by arteevraina** [comment]
Same thing happened with me.

**Comment by sibyl229** [comment]
@anishagg17 @anishagg17 Thank you for trying out the repo. Sorry about the issue. I am working on a solution to allow the development environment to run without some of the dependencies and credentials. It should be ready shortly. I will let you know then. Thanks for your interest and patience.

**Comment by arteevraina** [comment]
@sibyl229 there is also some issue in channel's irc link in GSOC's organisation page. It only shows 2 users .Can you help us with it?

**Comment by sibyl229** [comment]
@arteevraina I don't know how much that IRC is being monitored. I think it might be better to reach out to the mentors of individual projects directly.

**Comment by sibyl229** [comment]
@anishagg17 @arteevraina Instructions to setup a development environment is now available here: https://github.com/WormBase/website-public#experimental-development-environment---local-option 
There is likely rough edges. If you have any question, please feel free to ask. Thanks for your interest.

**Comment by anishagg17** [comment]
@sibyl229 why don't we have a a gitter or slack channel ?
All other organisations have such channels so that contributors can also discuss among themselves in case mentor is busy. It would help a lot as more than 1 person would be able to suggest changes/solutions

**Comment by sibyl229** [comment]
@anishagg17 thanks for your feedback! I guess we haven't worked much with community contributors before. Internally we do communicate over Slack. I will discuss with the organizer, but it probably won't be for this round of GSoC.

Also, I relied to everyone who has reached out to me over email. But I don't think I saw your name. If you haven't received a reply from me. Would you mind emailing me again? Thanks!
